// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: proto/event_service.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	anypb "google.golang.org/protobuf/types/known/anypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type EventSubscription struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EventSubscription) Reset() {
	*x = EventSubscription{}
	mi := &file_proto_event_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EventSubscription) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EventSubscription) ProtoMessage() {}

func (x *EventSubscription) ProtoReflect() protoreflect.Message {
	mi := &file_proto_event_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EventSubscription.ProtoReflect.Descriptor instead.
func (*EventSubscription) Descriptor() ([]byte, []int) {
	return file_proto_event_service_proto_rawDescGZIP(), []int{0}
}

func (x *EventSubscription) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type EventDelivery struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Args          []*anypb.Any           `protobuf:"bytes,1,rep,name=args,proto3" json:"args,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EventDelivery) Reset() {
	*x = EventDelivery{}
	mi := &file_proto_event_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EventDelivery) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EventDelivery) ProtoMessage() {}

func (x *EventDelivery) ProtoReflect() protoreflect.Message {
	mi := &file_proto_event_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EventDelivery.ProtoReflect.Descriptor instead.
func (*EventDelivery) Descriptor() ([]byte, []int) {
	return file_proto_event_service_proto_rawDescGZIP(), []int{1}
}

func (x *EventDelivery) GetArgs() []*anypb.Any {
	if x != nil {
		return x.Args
	}
	return nil
}

var File_proto_event_service_proto protoreflect.FileDescriptor

const file_proto_event_service_proto_rawDesc = "" +
	"\n" +
	"\x19proto/event_service.proto\x12\bprotobuf\x1a\x19google/protobuf/any.proto\"'\n" +
	"\x11EventSubscription\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\"9\n" +
	"\rEventDelivery\x12(\n" +
	"\x04args\x18\x01 \x03(\v2\x14.google.protobuf.AnyR\x04args2S\n" +
	"\fEventService\x12C\n" +
	"\tSubscribe\x12\x1b.protobuf.EventSubscription\x1a\x17.protobuf.EventDelivery0\x01B(Z&github.com/ChrisEineke/go-events/protob\x06proto3"

var (
	file_proto_event_service_proto_rawDescOnce sync.Once
	file_proto_event_service_proto_rawDescData []byte
)

func file_proto_event_service_proto_rawDescGZIP() []byte {
	file_proto_event_service_proto_rawDescOnce.Do(func() {
		file_proto_event_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_event_service_proto_rawDesc), len(file_proto_event_service_proto_rawDesc)))
	})
	return file_proto_event_service_proto_rawDescData
}

var file_proto_event_service_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_proto_event_service_proto_goTypes = []any{
	(*EventSubscription)(nil), // 0: protobuf.EventSubscription
	(*EventDelivery)(nil),     // 1: protobuf.EventDelivery
	(*anypb.Any)(nil),         // 2: google.protobuf.Any
}
var file_proto_event_service_proto_depIdxs = []int32{
	2, // 0: protobuf.EventDelivery.args:type_name -> google.protobuf.Any
	0, // 1: protobuf.EventService.Subscribe:input_type -> protobuf.EventSubscription
	1, // 2: protobuf.EventService.Subscribe:output_type -> protobuf.EventDelivery
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_proto_event_service_proto_init() }
func file_proto_event_service_proto_init() {
	if File_proto_event_service_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_event_service_proto_rawDesc), len(file_proto_event_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_event_service_proto_goTypes,
		DependencyIndexes: file_proto_event_service_proto_depIdxs,
		MessageInfos:      file_proto_event_service_proto_msgTypes,
	}.Build()
	File_proto_event_service_proto = out.File
	file_proto_event_service_proto_goTypes = nil
	file_proto_event_service_proto_depIdxs = nil
}
